title: "" # the name of your site, e.g. ACME Corp.
#tagline: ""
# email: 
# description: >- # this means to ignore newlines until "baseurl:"
 # Add description here
# author: name
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1

# more on https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

sass:
    load_paths:
        - _sass
        -  /Users/kallyannybun/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bootstrap-4.3.1/assets/stylesheets # bundle info bootstrap

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap