title: Mrik B. # the name of your site, e.g. ACME Corp.
tagline: Mrik B. - Content Creator
# email: 
description: Digital Communication, Photography & Videography - My work is to create, edit and promote meaningful contents, photos and videos. 
baseurl: / # the subpath of your site, e.g. /blog
url: "https://mrikb.com" # the base hostname & protocol for your site, e.g. http://example.com
# google_analytics: UA-111111111-1
twitter:
  username: mrik_b
  card: summary

# more on https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap